language: bash
services: docker

env:
  global:
  matrix:
  - SUITE=xenial VERSION=9
  - SUITE=xenial VERSION=8
  - SUITE=xenial VERSION=7
  - SUITE=wheezy VERSION=7
  - SUITE=wheezy VERSION=6
  - SUITE=wheezy VERSION=6 VARIANT=slim
  - SUITE=trusty VERSION=8
  - SUITE=trusty VERSION=7
  - SUITE=trusty VERSION=6
  - SUITE=stretch VERSION=9
  - SUITE=stretch VERSION=9 VARIANT=slim
  - SUITE=stretch VERSION=8
  - SUITE=stretch VERSION=8 VARIANT=slim
  - SUITE=stretch VERSION=8 VARIANT=alpine
  - SUITE=sid VERSION=11
  - SUITE=sid VERSION=11 VARIANT=slim
  - SUITE=sid VERSION=10
  - SUITE=sid VERSION=10 VARIANT=slim
  - SUITE=sid VERSION=8
  - SUITE=sid VERSION=8 VARIANT=slim
  - SUITE=jessie VERSION=8
  - SUITE=jessie VERSION=8 VARIANT=slim
  - SUITE=jessie VERSION=7
  - SUITE=jessie VERSION=7 VARIANT=slim
  - SUITE=jessie VERSION=7 VARIANT=alpine
  - SUITE=buster VERSION=11
  - SUITE=buster VERSION=11 VARIANT=slim
  - SUITE=buster VERSION=10
  - SUITE=buster VERSION=10 VARIANT=slim
  - SUITE=buster VERSION=8
  - SUITE=buster VERSION=8 VARIANT=slim
  - SUITE=bionic VERSION=11
  - SUITE=bionic VERSION=8
  - SUITE=artful VERSION=9
  - SUITE=artful VERSION=8

matrix:
  fast_finish: true
  allow_failures:
  - env: SUITE=sid VERSION=11
  - env: SUITE=sid VERSION=11 VARIANT=slim
  - env: SUITE=xenial VERSION=9

branches:
  only:
  - openjdk

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$SUITE/$VERSION"
  - imageBase="${TRAVIS_REPO_SLUG%%/*}/openjdk:$SUITE-$VERSION"
  - imageSuffix="${VARIANT:+-$VARIANT}"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      travis_retry docker build -t "$imageBase-jdk$imageSuffix" "jdk${VARIANT:+/$VARIANT}"
      travis_retry docker build -t "$imageBase-jre$imageSuffix" "jre${VARIANT:+/$VARIANT}"
      ~/official-images/test/run.sh "$imageBase-jdk$imageSuffix" "$imageBase-jre$imageSuffix"
    )

after_script:
  - docker images

# vim:set et ts=2 sw=2:
