language: bash

# for secret experimental features ;)
sudo: 9000

env:
  - VERSION=openjdk-8-jre
  - VERSION=openjdk-8-jdk
  - VERSION=openjdk-7-jre
  - VERSION=openjdk-7-jdk
  - VERSION=openjdk-6-jre
  - VERSION=openjdk-6-jdk

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="java:$VERSION"

script:
  - docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
