language: bash
services: docker

env:
  global:
  matrix:
  - VERSION=java-8-jdk/artful
  - VERSION=java-8-jdk/bionic
  - VERSION=java-8-jdk/buster
  - VERSION=java-8-jdk/jessie
  - VERSION=java-8-jdk/sid
  - VERSION=java-8-jdk/stretch
  - VERSION=java-8-jdk/trusty
  - VERSION=java-8-jdk/wheezy
  - VERSION=java-8-jdk/xenial
  - VERSION=java-9-jdk/artful
  - VERSION=java-9-jdk/bionic
  - VERSION=java-9-jdk/buster
  - VERSION=java-9-jdk/jessie
  - VERSION=java-9-jdk/sid
  - VERSION=java-9-jdk/stretch
  - VERSION=java-9-jdk/trusty
  - VERSION=java-9-jdk/wheezy
  - VERSION=java-9-jdk/xenial

matrix:
  fast_finish: true
  allow_failures:

branches:
  only:
  - master

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - if [ -n "$(echo $VERSION | grep openjdk)" ]; then
      image="${TRAVIS_REPO_SLUG%%/*}/java:${VERSION##*/}-${VERSION%%/*}";
    else
      image="${TRAVIS_REPO_SLUG%%/*}/java:${VERSION##*/}-oracle-${VERSION%%/*}";
    fi

script:
  - docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
