language: bash
services: docker

env:
  global:
  matrix:
  - VERSION=6-jdk/trusty
  - VERSION=6-jdk/wheezy
  - VERSION=6-jdk/wheezy VARIANT=slim
  - VERSION=6-jre/trusty
  - VERSION=6-jre/wheezy
  - VERSION=6-jre/wheezy VARIANT=slim
  - VERSION=7-jdk/jessie
  - VERSION=7-jdk/jessie VARIANT=alpine
  - VERSION=7-jdk/jessie VARIANT=slim
  - VERSION=7-jdk/trusty
  - VERSION=7-jdk/wheezy
  - VERSION=7-jre/jessie
  - VERSION=7-jre/jessie VARIANT=alpine
  - VERSION=7-jre/jessie VARIANT=slim
  - VERSION=7-jre/trusty
  - VERSION=7-jre/wheezy
  - VERSION=8-jdk/artful
  - VERSION=8-jdk/bionic
  - VERSION=8-jdk/buster
  - VERSION=8-jdk/buster VARIANT=slim
  - VERSION=8-jdk/jessie
  - VERSION=8-jdk/jessie VARIANT=slim
  - VERSION=8-jdk/sid
  - VERSION=8-jdk/sid VARIANT=slim
  - VERSION=8-jdk/stretch
  - VERSION=8-jdk/stretch VARIANT=alpine
  - VERSION=8-jdk/stretch VARIANT=slim
  - VERSION=8-jdk/xenial
  - VERSION=8-jdk/zesty
  - VERSION=8-jre/artful
  - VERSION=8-jre/bionic
  - VERSION=8-jre/buster
  - VERSION=8-jre/buster VARIANT=slim
  - VERSION=8-jre/jessie
  - VERSION=8-jre/jessie VARIANT=slim
  - VERSION=8-jre/sid
  - VERSION=8-jre/sid VARIANT=slim
  - VERSION=8-jre/stretch
  - VERSION=8-jre/stretch VARIANT=alpine
  - VERSION=8-jre/stretch VARIANT=slim
  - VERSION=8-jre/xenial
  - VERSION=8-jre/zesty
  - VERSION=9-jdk/artful
  - VERSION=9-jdk/bionic
  - VERSION=9-jdk/buster
  - VERSION=9-jdk/buster VARIANT=slim
  - VERSION=9-jdk/sid
  - VERSION=9-jdk/sid VARIANT=slim
  - VERSION=9-jdk/stretch
  - VERSION=9-jdk/stretch VARIANT=slim
  - VERSION=9-jdk/xenial
  - VERSION=9-jdk/zesty
  - VERSION=9-jre/artful
  - VERSION=9-jre/bionic
  - VERSION=9-jre/buster
  - VERSION=9-jre/buster VARIANT=slim
  - VERSION=9-jre/sid
  - VERSION=9-jre/sid VARIANT=slim
  - VERSION=9-jre/stretch
  - VERSION=9-jre/stretch VARIANT=slim
  - VERSION=9-jre/xenial
  - VERSION=9-jre/zesty

matrix:
  fast_finish: true
  allow_failures:
  - env: VERSION=9-jdk/xenial
  - env: VERSION=9-jre/xenial

branches:
  only:
  - openjdk

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "${VERSION}${VARIANT:+/$VARIANT}"
  - image="${TRAVIS_REPO_SLUG%%/*}/openjdk:${VERSION##*/}-${VERSION%%/*}${VARIANT:+-$VARIANT}";

script:
  - travis_retry docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
